		"#include<bits/stdc++.h>",
		"using namespace std;",
		"#define endl '\\n'",
		"#define int long long",
		"namespace gtx{",
		"//\tFast IO",
		"\tvoid read(int &x){",
		"\t\tx = 0;int h = 1;char tmp;",
		"\t\tdo{tmp=getchar();if(tmp=='-')h*=-1;}while(!isdigit(tmp));",
		"\t\twhile(isdigit(tmp)) x*=10,x+=tmp-'0',tmp=getchar();",
		"\t\tx*=h;",
		"\t}",
		"\tvoid read(char &x){do{x=getchar();}while(x==' '||x=='\\n'||x=='\\r');}",
		"\tvoid write(char x){putchar(x);}",
		"\tvoid write(int x){",
		"\t\tif(x<0) putchar('-'),x=-x;int st[200]={0},tot=0;",
		"\t\tdo{st[++tot]=x%10,x/=10;} while(x);",
		"\t\twhile(tot){putchar(st[tot--]+'0');};",
		"\t}",
		"\tvoid write(int x,char y){write(x);write(y);}",
		"\tsigned main(){",
		"\t\t$0",
		"\t\treturn 0;",
		"\t}",
		"}",
		"signed main(){",
		"// \tfreopen(\".in\",\"r\",stdin);",
		"// \tfreopen(\".out\",\"w\",stdout);",
		"//\tios::sync_with_stdio(0);cin.tie(0);cout.tie(0);",
		"\tint T = 1;",
		"//\tgtx::read(T);",
		"\twhile(T--) gtx::main();",
		"\treturn 0;",
		"}",
		"